# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :test_slack do
    #increment_build_number
    version     = get_version_number(xcodeproj: "Ao Dispor.xcodeproj")
    build       = get_build_number(xcodeproj: "Ao Dispor.xcodeproj")
    slack(
      default_payloads: [],
      use_webhook_configured_username_and_icon: true,
      message: "Nova compilação submetida para o Test Flight. Versão: *#{version}* (#{build})"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Ao Dispor") # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    version     = get_version_number(xcodeproj: "../Ao Dispor.xcodeproj")
    build       = get_build_number(xcodeproj: "../Ao Dispor.xcodeproj")
    slack(
      default_payloads: [],
      use_webhook_configured_username_and_icon: true,
      message: "Nova compilação submetida para o Test Flight. Versão: *#{version}* (#{build})"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Ao Dispor") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
